version: '3.8'

services:
  theology-db:
    image: ankane/pgvector:latest
    container_name: semantic-pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: semantic_theology
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  theology-db-admin:
    image: dpage/pgadmin4
    container_name: semantic-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@teologia.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  semantic-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: semantic-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://theology-db:5432/semantic_theology
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - theology-db

  semantic-ui:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: semantic-ui
    ports:
      - "4200:80"
    depends_on:
      - semantic-api

volumes:
  pgdata:
