spring:
  application:
    name: semantic-api
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/semantic_theology
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Quando usarmos o Docker-compose, a URL de DB será theology-db ao invés de localhost

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:dummy-key-for-local-development}
      chat:
        options:
          model: gpt-3.5-turbo
